name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
      
    runs-on: self-hosted
    environment: Prod
    steps:
    - uses: actions/checkout@v3
    - run: dotnet build --configuration Release .\Europium.sln
    - run: New-Item -Name Europium\bin\Release\net6.0\appconfig.json -ItemType File
    - run: (echo '${{ secrets.CONFIG }}') > Europium\bin\Release\net6.0\appconfig.json
    - run: taskkill /IM Europium.exe /F /FI "STATUS eq RUNNING"
    - run: cd Europium/bin/Release/net6.0/ ; RUNNER_TRACKING_ID="" ; ./launcher.bat
    #- run: cd Europium/bin/Release/net6.0/ ; Start-Process Europium.exe -ArgumentList "--urls=http://localhost:1010"
    #- run: cd Europium/bin/Release/net6.0/ ; RUNNER_TRACKING_ID="" ; start Europium.exe --urls=http://localhost:1010
    