name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
      
    runs-on: self-hosted
    environment: Prod
    steps:
    - name: Get git code
      uses: actions/checkout@v3

    - name: Build
      run: dotnet build --configuration Release .\Europium.sln

    - run: New-Item -Name ${{ vars.APP_CONFIG_FILE_PATH }} -ItemType File
    - run: (echo '${{ secrets.CONFIG }}') > ${{ vars.START_SERVER_BATCH_PATH }}
    - run: taskkill /IM Europium.exe /F
    - run: schtasks /create /tn "${{ vars.PROCESS_NAME }}" /tr "${{ vars.APP_CONFIG_FILE_PATH }}" /sc once /sd 01/01/2099 /st 23:59 /F
    - run: schtasks /run /tn "${{ vars.PROCESS_NAME }}"
    