name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
      
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: dotnet build .\Europium.sln
    
