name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
      
    runs-on: self-hosted
    environment: Prod
    steps:
    - uses: actions/checkout@v3
    - run: New-Item -Name appconfig.json -ItemType File
    - run: (echo ${{ secrets.CONFIG }}) > appconfig.json
    - run: dotnet build --configuration Release .\Europium.sln
    
