name: Europium Serverstart

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    
    runs-on: self-hosted
    environment: Prod
    steps:
      - name: Close Server
        run: taskkill /IM Europium.exe /F
        
      - name: Get last version from GitHub
        uses: actions/checkout@v3

      - name: Compile
        run: dotnet build --configuration Release .\Europium.sln

      - name: Create config file
        run: |
             New-Item -Name ${{ vars.APP_CONFIG_FILE_PATH }} -ItemType File
             (echo '${{ secrets.CONFIG }}') > ${{ vars.APP_CONFIG_FILE_PATH }}

      - name: Create server execution
        run: |
             New-Item -Name ${{ vars.START_SERVER_BATCH_PATH }} -ItemType File
             Set-Content -Path ${{ vars.START_SERVER_BATCH_PATH }} -Value '${{ vars.START_SERVER_SCRIPT }}'

      - name: Creater server scheduled task
        run: schtasks /create /tn "${{ vars.PROCESS_NAME }}" /tr "${{ vars.START_SERVER_BATCH_FULL_PATH }}" /sc ONSTART /F
        
      - name: Launch server
        run: schtasks /run /tn "${{ vars.PROCESS_NAME }}"